In [1]:
import numpy as np

In [2]:
from sklearn.datasets import load_iris

In [3]:
iris = load_iris()

In [4]:
type(iris)

sklearn.utils.Bunch

In [6]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [7]:
X = iris.data
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [8]:
y = iris.target
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [10]:
# Want to use one-hot-encoding to use in Keras
# Class_0 --> [1,0,0]
# Class_1 --> [0,1,0]
# Class_2 --> [0,0,1]

In [11]:
from keras.utils import to_categorical

In [12]:
y = to_categorical(y)
y.shape

(150, 3)

In [13]:
y

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [16]:
# Standardize data

In [17]:
from sklearn.preprocessing import MinMaxScaler

In [18]:
# np.array([5,10,15,20])/20

array([0.25, 0.5 , 0.75, 1.  ])

In [19]:
scaler_obj = MinMaxScaler()

In [20]:
# Only fit to the training features
scaler_obj.fit(X_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [21]:
scaled_X_train = scaler_obj.transform(X_train)
scaled_X_test = scaler_obj.transform(X_test)

In [22]:
from keras.models import Sequential
from keras.layers import Dense

In [25]:
model = Sequential()
model.add(Dense(units=8, input_dim=4, activation='relu'))
model.add(Dense(units=8, input_dim=4, activation='relu'))
model.add(Dense(units=3, activation='softmax'))
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [26]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_7 (Dense)              (None, 8)                 40        
_________________________________________________________________
dense_8 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_9 (Dense)              (None, 3)                 27        
Total params: 139
Trainable params: 139
Non-trainable params: 0
_________________________________________________________________


In [27]:
#epochs is the number of times the network "runs" through the entire training dataset
# verbose is the amount of info to output
model.fit(scaled_X_train,y_train,epochs=150,verbose=2)

Instructions for updating:
Use tf.cast instead.
Epoch 1/150
 - 2s - loss: 1.2513 - acc: 0.3100
Epoch 2/150
 - 0s - loss: 1.2316 - acc: 0.3100
Epoch 3/150
 - 0s - loss: 1.2108 - acc: 0.3100
Epoch 4/150
 - 0s - loss: 1.1914 - acc: 0.3000
Epoch 5/150
 - 0s - loss: 1.1726 - acc: 0.3000
Epoch 6/150
 - 0s - loss: 1.1540 - acc: 0.3000
Epoch 7/150
 - 0s - loss: 1.1365 - acc: 0.3100
Epoch 8/150
 - 0s - loss: 1.1197 - acc: 0.3100
Epoch 9/150
 - 0s - loss: 1.1027 - acc: 0.5300
Epoch 10/150
 - 0s - loss: 1.0862 - acc: 0.6300
Epoch 11/150
 - 0s - loss: 1.0710 - acc: 0.6400
Epoch 12/150
 - 0s - loss: 1.0558 - acc: 0.6400
Epoch 13/150
 - 0s - loss: 1.0417 - acc: 0.6400
Epoch 14/150
 - 0s - loss: 1.0279 - acc: 0.6400
Epoch 15/150
 - 0s - loss: 1.0147 - acc: 0.6400
Epoch 16/150
 - 0s - loss: 1.0014 - acc: 0.6400
Epoch 17/150
 - 0s - loss: 0.9888 - acc: 0.6400
Epoch 18/150
 - 0s - loss: 0.9763 - acc: 0.6500
Epoch 19/150
 - 0s - loss: 0.9639 - acc: 0.6500
Epoch 20/150
 - 0s - loss: 0.9517 - acc: 0.6500
E

In [29]:
model.predict_classes(scaled_X_test)

array([1, 0, 2, 1, 2, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 1,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2])

In [30]:
predictions = model.predict_classes(scaled_X_test)
y_test.argmax(axis=1)

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2])

In [33]:
import pandas as pd
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [38]:
display(pd.DataFrame(confusion_matrix(y_test.argmax(axis=1),predictions), 
                            index=['True0','True1', 'True2'], 
                            columns=['Pred0','Pred1', 'Pred2']))
print(classification_report(y_test.argmax(axis=1),predictions))
print('Accuracy Score:', accuracy_score(y_test.argmax(axis=1),predictions))

Pred0  Pred1  Pred2
True0     19      0      0
True1      0     13      2
True2      0      1     15

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       0.93      0.87      0.90        15
           2       0.88      0.94      0.91        16

   micro avg       0.94      0.94      0.94        50
   macro avg       0.94      0.93      0.94        50
weighted avg       0.94      0.94      0.94        50

Accuracy Score: 0.94


In [39]:
# save the results of the model to be re-used
model.save('myfirstmodel.h5')

In [40]:
# load the model
from keras.models import load_model

In [42]:
new_model = load_model('myfirstmodel.h5')

# Recurrent Neural Networks
> Specifically designed to work with sequence data
* Time series
* Sentences (NLP)
* Audio
* Car Trajectories

<img src='feed_forward_neuron.png'>
<img src='recur_neuron.png'>
<img src='recur_neuron_1.png'>

**Memory Cells:** Nodes that are a function of inputs from previous time steps

<img src='recur_layer.png'>
<img src='recur_layer_1.png'>

# LSTM & GRU
* Long-short term memory
* 

> Help to reduce the "forgetfullness" of RNNs as what was input at $t_{0}$ may lose its influence at $t_{i+j}$

<img src='lstm_cell.png'>

**Input:**
1. $C_{t-1}$: Cell state at $t-1$
2. $h_{t-1}$: outcome of previous cell
3. $x_{t}$: factor of relevance

### First Step: Forget Gate Layer
* We decide what information we are going to "forget", or "throw away", from the cell state
<img src='forget_gate_layer.png'>

### Second Step:
* We decide what to store
<img src='lstm_stage_2.png'>

### Third Step:
* We update the cell state (to send to the next cell state)
<img src='lstm_stage_3.png'>

### Fourth Step:
* We output $h_{t}$
<img src='lstm_stage_4.png'>

**Different kind of LSTMs:**
1. Peephole
2. Gated Recurrent Unit (GRU)

**Peephole**
<img src='lstm_peep.png'>
**GRU**
<img src='lstm_GRU.png'>

# Text Generation with LSTMs with Keras and Python

In [1]:
def read_file(filepath):
    with open(filepath) as f:
        str_text = f.read()
        
        return str_text

In [2]:
# Token and Clean the text

In [3]:
import spacy

In [4]:
# minimize the load by specifiying what to disable
nlp = spacy.load('en',disable=['parser','tagger','ner'])

In [5]:
nlp.max_length = 1198623

In [6]:
def separate_punc(doc_text):
    import string
    return [token.text.lower() for token in nlp(doc_text) if token.text not in '\n\n \n\n\n!"-#$%&()--.*+,-/:;<=>?@[\\]^_`{|}~\t\n ']
#     return [token.text.lower() for token in nlp(doc_text) if token.text not in [string.punctuation, '\n\n \n\n\n!"']]

In [7]:
d = read_file('moby_dick_four_chapters.txt')

In [8]:
tokens = separate_punc(d)

In [9]:
len(tokens)

11394

In [10]:
# 25 words --> network predict #26

In [11]:
train_len = 25 + 1

text_sequences = []

for i in range(train_len,len(tokens)):
    seq = tokens[i-train_len:i]
    
    text_sequences.append(seq)

In [12]:
type(text_sequences)

list

In [13]:
# Each item in the list is composed of one word to the right of the previous, and less the first
# - shift the text one word right
for i in range(5):
    print(' '.join(text_sequences[i]))
    print()

call me ishmael some years ago never mind how long precisely having little or no money in my purse and nothing particular to interest me on

me ishmael some years ago never mind how long precisely having little or no money in my purse and nothing particular to interest me on shore

ishmael some years ago never mind how long precisely having little or no money in my purse and nothing particular to interest me on shore i

some years ago never mind how long precisely having little or no money in my purse and nothing particular to interest me on shore i thought

years ago never mind how long precisely having little or no money in my purse and nothing particular to interest me on shore i thought i



In [14]:
from keras.preprocessing.text import Tokenizer

ModuleNotFoundError: No module named 'keras'

In [16]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts(text_sequences)

In [17]:
sequences = tokenizer.texts_to_sequences(text_sequences)

In [18]:
sequences[0]

[964,
 14,
 265,
 51,
 263,
 416,
 87,
 222,
 129,
 111,
 962,
 262,
 50,
 43,
 37,
 321,
 7,
 23,
 555,
 3,
 150,
 261,
 6,
 2704,
 14,
 24]

In [19]:
tokenizer.index_word[964]

'call'

In [20]:
for i in sequences[0]:
    print(f"{i}: {tokenizer.index_word[i]}")

964: call
14: me
265: ishmael
51: some
263: years
416: ago
87: never
222: mind
129: how
111: long
962: precisely
262: having
50: little
43: or
37: no
321: money
7: in
23: my
555: purse
3: and
150: nothing
261: particular
6: to
2704: interest
14: me
24: on


In [21]:
tokenizer.word_counts

OrderedDict([('call', 27),
             ('me', 2471),
             ('ishmael', 133),
             ('some', 758),
             ('years', 135),
             ('ago', 84),
             ('never', 449),
             ('mind', 164),
             ('how', 321),
             ('long', 374),
             ('precisely', 37),
             ('having', 142),
             ('little', 767),
             ('or', 950),
             ('no', 1029),
             ('money', 120),
             ('in', 5647),
             ('my', 1812),
             ('purse', 71),
             ('and', 9646),
             ('nothing', 281),
             ('particular', 152),
             ('to', 6497),
             ('interest', 24),
             ('on', 1716),
             ('shore', 26),
             ('i', 7176),
             ('thought', 676),
             ('would', 702),
             ('sail', 104),
             ('about', 1014),
             ('a', 10377),
             ('see', 442),
             ('the', 15566),
             ('watery', 26),
  

In [22]:
vocabulary_size = len(tokenizer.word_counts)

In [23]:
vocabulary_size

2709

In [24]:
# Want this to be a matrix
type(sequences)

list

In [25]:
import numpy as np

In [26]:
sequences = np.array(sequences)

In [27]:
sequences

array([[ 964,   14,  265, ..., 2704,   14,   24],
       [  14,  265,   51, ...,   14,   24,  965],
       [ 265,   51,  263, ...,   24,  965,    5],
       ...,
       [ 960,   12,  168, ...,  264,   53,    2],
       [  12,  168, 2703, ...,   53,    2, 2709],
       [ 168, 2703,    3, ...,    2, 2709,   26]])

In [28]:
from keras.utils import to_categorical

In [29]:
sequences[:,:-1]

array([[ 964,   14,  265, ...,    6, 2704,   14],
       [  14,  265,   51, ..., 2704,   14,   24],
       [ 265,   51,  263, ...,   14,   24,  965],
       ...,
       [ 960,   12,  168, ...,   11,  264,   53],
       [  12,  168, 2703, ...,  264,   53,    2],
       [ 168, 2703,    3, ...,   53,    2, 2709]])

In [30]:
sequences[:,-1]

array([  24,  965,    5, ...,    2, 2709,   26])

In [31]:
X = sequences[:,:-1]
y = sequences[:,-1]

In [32]:
vocabulary_size = len(tokenizer.word_counts)
y = to_categorical(y,num_classes=vocabulary_size+1)

In [33]:
seq_len = X.shape[1]

In [34]:
X.shape

(11368, 25)

In [35]:
from keras.models import Sequential
from keras.layers import Dense,LSTM,Embedding

In [36]:
def create_model(vocabulary_size,seq_len):
    
    model = Sequential()
    # turns positive integers into dense vectors of a fixed size
    model.add(Embedding(vocabulary_size,seq_len,input_length=seq_len))
    # Common to make this some multiple of your sequence length: seq_len*10 = units = #neurons
    model.add(LSTM(units=seq_len*10,return_sequences=True))
    model.add(LSTM(units=seq_len*10))
    model.add(Dense(units=seq_len*10, activation='relu'))
    
    # output of network
    model.add(Dense(vocabulary_size,activation='softmax'))
    
    model.compile(loss='categorical_crossentropy',optimizer='adam', metrics=['accuracy'])
    
    model.summary()
    
    return model

In [37]:
model = create_model(vocabulary_size+1,seq_len)

Instructions for updating:
Colocations handled automatically by placer.
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 25, 25)            67750     
_________________________________________________________________
lstm_1 (LSTM)                (None, 25, 250)           276000    
_________________________________________________________________
lstm_2 (LSTM)                (None, 250)               501000    
_________________________________________________________________
dense_1 (Dense)              (None, 250)               62750     
_________________________________________________________________
dense_2 (Dense)              (None, 2710)              680210    
Total params: 1,587,710
Trainable params: 1,587,710
Non-trainable params: 0
_________________________________________________________________


In [38]:
from pickle import dump,load

In [ ]:
model.fit(X,y,batch_size=128,epochs=2,verbose=1)

Instructions for updating:
Use tf.cast instead.
Epoch 1/2
