In [1]:
import numpy as np

In [2]:
from sklearn.datasets import load_iris

In [3]:
iris = load_iris()

In [4]:
type(iris)

sklearn.utils.Bunch

In [5]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [6]:
X = iris.data
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [7]:
y = iris.target
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [8]:
# Want to use one-hot-encoding to use in Keras
# Class_0 --> [1,0,0]
# Class_1 --> [0,1,0]
# Class_2 --> [0,0,1]

In [9]:
from tensorflow.keras.utils import to_categorical

/Users/daiglechris/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/Users/daiglechris/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/Users/daiglechris/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/Users/daiglechris/opt/anaconda3/lib/python3.7/site-

In [10]:
y = to_categorical(y)
y.shape

(150, 3)

In [11]:
y

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [14]:
# Standardize data

In [15]:
from sklearn.preprocessing import MinMaxScaler

In [16]:
# np.array([5,10,15,20])/20

In [17]:
scaler_obj = MinMaxScaler()

In [18]:
# Only fit to the training features
scaler_obj.fit(X_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [19]:
scaled_X_train = scaler_obj.transform(X_train)
scaled_X_test = scaler_obj.transform(X_test)

In [20]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [21]:
model = Sequential()
# Units: neurons/nodes
# Input_dim: number of features/factors/x-variables to be input
# activation: function for node
model.add(Dense(units=8, input_dim=4, activation='sigmoid'))
model.add(Dense(units=8, input_dim=4, activation='relu'))
model.add(Dense(units=8, input_dim=4, activation='relu'))
model.add(Dense(units=3, activation='softmax'))
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [22]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 8)                 40        
_________________________________________________________________
dense_1 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_2 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_3 (Dense)              (None, 3)                 27        
Total params: 211
Trainable params: 211
Non-trainable params: 0
_________________________________________________________________


In [23]:
#epochs is the number of times the network "runs" through the entire training dataset
# verbose is the amount of info to output
model.fit(scaled_X_train,y_train,epochs=700,verbose=2)

Epoch 1/700
100/100 - 0s - loss: 1.1119 - acc: 0.3100
Epoch 2/700
100/100 - 0s - loss: 1.1094 - acc: 0.3100
Epoch 3/700
100/100 - 0s - loss: 1.1083 - acc: 0.3100
Epoch 4/700
100/100 - 0s - loss: 1.1065 - acc: 0.3100
Epoch 5/700
100/100 - 0s - loss: 1.1057 - acc: 0.3100
Epoch 6/700
100/100 - 0s - loss: 1.1051 - acc: 0.3100
Epoch 7/700
100/100 - 0s - loss: 1.1041 - acc: 0.3100
Epoch 8/700
100/100 - 0s - loss: 1.1034 - acc: 0.3100
Epoch 9/700
100/100 - 0s - loss: 1.1023 - acc: 0.3100
Epoch 10/700
100/100 - 0s - loss: 1.1016 - acc: 0.3100
Epoch 11/700
100/100 - 0s - loss: 1.1008 - acc: 0.3000
Epoch 12/700
100/100 - 0s - loss: 1.1000 - acc: 0.1300
Epoch 13/700
100/100 - 0s - loss: 1.0996 - acc: 0.3400
Epoch 14/700
100/100 - 0s - loss: 1.0993 - acc: 0.3400
Epoch 15/700
100/100 - 0s - loss: 1.0988 - acc: 0.3400
Epoch 16/700
100/100 - 0s - loss: 1.0985 - acc: 0.3400
Epoch 17/700
100/100 - 0s - loss: 1.0982 - acc: 0.3400
Epoch 18/700
100/100 - 0s - loss: 1.0980 - acc: 0.3400
Epoch 19/700
100/10

100/100 - 0s - loss: 0.6924 - acc: 0.6400
Epoch 150/700
100/100 - 0s - loss: 0.6907 - acc: 0.6400
Epoch 151/700
100/100 - 0s - loss: 0.6887 - acc: 0.6400
Epoch 152/700
100/100 - 0s - loss: 0.6871 - acc: 0.6400
Epoch 153/700
100/100 - 0s - loss: 0.6855 - acc: 0.6300
Epoch 154/700
100/100 - 0s - loss: 0.6839 - acc: 0.6300
Epoch 155/700
100/100 - 0s - loss: 0.6824 - acc: 0.6300
Epoch 156/700
100/100 - 0s - loss: 0.6807 - acc: 0.6400
Epoch 157/700
100/100 - 0s - loss: 0.6791 - acc: 0.6400
Epoch 158/700
100/100 - 0s - loss: 0.6774 - acc: 0.6400
Epoch 159/700
100/100 - 0s - loss: 0.6759 - acc: 0.6400
Epoch 160/700
100/100 - 0s - loss: 0.6744 - acc: 0.6400
Epoch 161/700
100/100 - 0s - loss: 0.6730 - acc: 0.7500
Epoch 162/700
100/100 - 0s - loss: 0.6716 - acc: 0.7500
Epoch 163/700
100/100 - 0s - loss: 0.6702 - acc: 0.7500
Epoch 164/700
100/100 - 0s - loss: 0.6688 - acc: 0.7500
Epoch 165/700
100/100 - 0s - loss: 0.6674 - acc: 0.6900
Epoch 166/700
100/100 - 0s - loss: 0.6661 - acc: 0.6400
Epoch 

Epoch 296/700
100/100 - 0s - loss: 0.5738 - acc: 0.6600
Epoch 297/700
100/100 - 0s - loss: 0.5735 - acc: 0.6600
Epoch 298/700
100/100 - 0s - loss: 0.5730 - acc: 0.6600
Epoch 299/700
100/100 - 0s - loss: 0.5726 - acc: 0.6600
Epoch 300/700
100/100 - 0s - loss: 0.5722 - acc: 0.6600
Epoch 301/700
100/100 - 0s - loss: 0.5718 - acc: 0.6600
Epoch 302/700
100/100 - 0s - loss: 0.5714 - acc: 0.6600
Epoch 303/700
100/100 - 0s - loss: 0.5710 - acc: 0.6600
Epoch 304/700
100/100 - 0s - loss: 0.5706 - acc: 0.6600
Epoch 305/700
100/100 - 0s - loss: 0.5702 - acc: 0.6600
Epoch 306/700
100/100 - 0s - loss: 0.5698 - acc: 0.6600
Epoch 307/700
100/100 - 0s - loss: 0.5695 - acc: 0.6600
Epoch 308/700
100/100 - 0s - loss: 0.5691 - acc: 0.6600
Epoch 309/700
100/100 - 0s - loss: 0.5687 - acc: 0.6600
Epoch 310/700
100/100 - 0s - loss: 0.5683 - acc: 0.6600
Epoch 311/700
100/100 - 0s - loss: 0.5679 - acc: 0.6600
Epoch 312/700
100/100 - 0s - loss: 0.5676 - acc: 0.6600
Epoch 313/700
100/100 - 0s - loss: 0.5672 - acc:

Epoch 443/700
100/100 - 0s - loss: 0.4392 - acc: 0.9300
Epoch 444/700
100/100 - 0s - loss: 0.4382 - acc: 0.9300
Epoch 445/700
100/100 - 0s - loss: 0.4358 - acc: 0.9300
Epoch 446/700
100/100 - 0s - loss: 0.4322 - acc: 0.9400
Epoch 447/700
100/100 - 0s - loss: 0.4286 - acc: 0.9300
Epoch 448/700
100/100 - 0s - loss: 0.4274 - acc: 0.9300
Epoch 449/700
100/100 - 0s - loss: 0.4276 - acc: 0.9300
Epoch 450/700
100/100 - 0s - loss: 0.4250 - acc: 0.9300
Epoch 451/700
100/100 - 0s - loss: 0.4215 - acc: 0.9300
Epoch 452/700
100/100 - 0s - loss: 0.4188 - acc: 0.9200
Epoch 453/700
100/100 - 0s - loss: 0.4171 - acc: 0.9300
Epoch 454/700
100/100 - 0s - loss: 0.4158 - acc: 0.9400
Epoch 455/700
100/100 - 0s - loss: 0.4138 - acc: 0.9400
Epoch 456/700
100/100 - 0s - loss: 0.4122 - acc: 0.9300
Epoch 457/700
100/100 - 0s - loss: 0.4100 - acc: 0.9400
Epoch 458/700
100/100 - 0s - loss: 0.4076 - acc: 0.9400
Epoch 459/700
100/100 - 0s - loss: 0.4075 - acc: 0.9400
Epoch 460/700
100/100 - 0s - loss: 0.4054 - acc:

Epoch 590/700
100/100 - 0s - loss: 0.2327 - acc: 0.9700
Epoch 591/700
100/100 - 0s - loss: 0.2317 - acc: 0.9700
Epoch 592/700
100/100 - 0s - loss: 0.2296 - acc: 0.9500
Epoch 593/700
100/100 - 0s - loss: 0.2282 - acc: 0.9500
Epoch 594/700
100/100 - 0s - loss: 0.2295 - acc: 0.9600
Epoch 595/700
100/100 - 0s - loss: 0.2291 - acc: 0.9600
Epoch 596/700
100/100 - 0s - loss: 0.2263 - acc: 0.9500
Epoch 597/700
100/100 - 0s - loss: 0.2258 - acc: 0.9500
Epoch 598/700
100/100 - 0s - loss: 0.2254 - acc: 0.9700
Epoch 599/700
100/100 - 0s - loss: 0.2231 - acc: 0.9500
Epoch 600/700
100/100 - 0s - loss: 0.2238 - acc: 0.9500
Epoch 601/700
100/100 - 0s - loss: 0.2223 - acc: 0.9500
Epoch 602/700
100/100 - 0s - loss: 0.2210 - acc: 0.9500
Epoch 603/700
100/100 - 0s - loss: 0.2203 - acc: 0.9500
Epoch 604/700
100/100 - 0s - loss: 0.2199 - acc: 0.9500
Epoch 605/700
100/100 - 0s - loss: 0.2187 - acc: 0.9500
Epoch 606/700
100/100 - 0s - loss: 0.2184 - acc: 0.9500
Epoch 607/700
100/100 - 0s - loss: 0.2172 - acc:

In [24]:
model.predict_classes(scaled_X_test)

array([1, 0, 2, 1, 1, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 1,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 1, 2, 1, 2])

In [25]:
predictions = model.predict_classes(scaled_X_test)
y_test.argmax(axis=1)

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2])

In [26]:
import pandas as pd
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [27]:
display(pd.DataFrame(confusion_matrix(y_test.argmax(axis=1),predictions), 
                            index=['True0','True1', 'True2'], 
                            columns=['Pred0','Pred1', 'Pred2']))
print(classification_report(y_test.argmax(axis=1),predictions))
print('Accuracy Score:', accuracy_score(y_test.argmax(axis=1),predictions))

Pred0  Pred1  Pred2
True0     19      0      0
True1      0     14      1
True2      0      2     14

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       0.88      0.93      0.90        15
           2       0.93      0.88      0.90        16

    accuracy                           0.94        50
   macro avg       0.94      0.94      0.94        50
weighted avg       0.94      0.94      0.94        50

Accuracy Score: 0.94


In [28]:
# save the results of the model to be re-used
model.save('myfirstmodel.h5')

In [29]:
# load the model
from tensorflow.keras.models import load_model

In [30]:
new_model = load_model('myfirstmodel.h5')

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [31]:
new_model.predict_classes(scaled_X_test)

array([1, 0, 2, 1, 1, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 1,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 1, 2, 1, 2])

# Recurrent Neural Networks
> Specifically designed to work with sequence data
* Time series
* Sentences (NLP)
* Audio
* Car Trajectories

<img src='feed_forward_neuron.png'>
<img src='recur_neuron.png'>
<img src='recur_neuron_1.png'>

**Memory Cells:** Nodes that are a function of inputs from previous time steps

<img src='recur_layer.png'>
<img src='recur_layer_1.png'>

# LSTM & GRU
* Long-short term memory
* 

> Help to reduce the "forgetfullness" of RNNs as what was input at $t_{0}$ may lose its influence at $t_{i+j}$

<img src='lstm_cell.png'>

**Input:**
1. $C_{t-1}$: Cell state at $t-1$
2. $h_{t-1}$: outcome of previous cell
3. $x_{t}$: factor of relevance

### First Step: Forget Gate Layer
* We decide what information we are going to "forget", or "throw away", from the cell state
<img src='forget_gate_layer.png'>

### Second Step:
* We decide what to store
<img src='lstm_stage_2.png'>

### Third Step:
* We update the cell state (to send to the next cell state)
<img src='lstm_stage_3.png'>

### Fourth Step:
* We output $h_{t}$
<img src='lstm_stage_4.png'>

**Different kind of LSTMs:**
1. Peephole
2. Gated Recurrent Unit (GRU)

**Peephole**
<img src='lstm_peep.png'>
**GRU**
<img src='lstm_GRU.png'>

# Text Generation with LSTMs with Keras and Python

In [32]:
def read_file(filepath):
    with open(filepath) as f:
        str_text = f.read()
        
        return str_text

In [33]:
# Token and Clean the text

In [34]:
import spacy

In [35]:
# minimize the load by specifiying what to disable
nlp = spacy.load('en_core_web_lg')

In [36]:
nlp.max_length = 1198623

In [37]:
def separate_punc(doc_text):
    import string
    return [token.text.lower() for token in nlp(doc_text) if token.text not in '\n\n \n\n\n!"-#$%&()--.*+,-/:;<=>?@[\\]^_`{|}~\t\n ']
#     return [token.text.lower() for token in nlp(doc_text) if token.text not in [string.punctuation, '\n\n \n\n\n!"']]

In [38]:
d = read_file('moby_dick_four_chapters.txt')

In [39]:
tokens = separate_punc(d)

In [40]:
len(tokens)

11338

In [41]:
# 25 words --> network predict #26

In [42]:
train_len = 25 + 1

text_sequences = []

for i in range(train_len,len(tokens)):
    seq = tokens[i-train_len:i]
    
    text_sequences.append(seq)

In [43]:
type(text_sequences)

list

In [44]:
# Each item in the list is composed of one word to the right of the previous, and less the first
# - shift the text one word right
for i in range(5):
    print(' '.join(text_sequences[i]))
    print()

call me ishmael some years ago never mind how long precisely having little or no money in my purse and nothing particular to interest me on

me ishmael some years ago never mind how long precisely having little or no money in my purse and nothing particular to interest me on shore

ishmael some years ago never mind how long precisely having little or no money in my purse and nothing particular to interest me on shore i

some years ago never mind how long precisely having little or no money in my purse and nothing particular to interest me on shore i thought

years ago never mind how long precisely having little or no money in my purse and nothing particular to interest me on shore i thought i



In [45]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [46]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts(text_sequences)

In [47]:
sequences = tokenizer.texts_to_sequences(text_sequences)

In [48]:
sequences[0]

[956,
 14,
 263,
 51,
 261,
 408,
 87,
 219,
 129,
 111,
 954,
 260,
 50,
 43,
 38,
 315,
 7,
 23,
 546,
 3,
 150,
 259,
 6,
 2712,
 14,
 24]

In [49]:
tokenizer.index_word[956]

'call'

In [50]:
for i in sequences[0]:
    print(f"{i}: {tokenizer.index_word[i]}")

956: call
14: me
263: ishmael
51: some
261: years
408: ago
87: never
219: mind
129: how
111: long
954: precisely
260: having
50: little
43: or
38: no
315: money
7: in
23: my
546: purse
3: and
150: nothing
259: particular
6: to
2712: interest
14: me
24: on


In [51]:
tokenizer.word_counts

OrderedDict([('call', 27),
             ('me', 2471),
             ('ishmael', 133),
             ('some', 758),
             ('years', 135),
             ('ago', 84),
             ('never', 449),
             ('mind', 164),
             ('how', 321),
             ('long', 374),
             ('precisely', 37),
             ('having', 142),
             ('little', 767),
             ('or', 950),
             ('no', 1003),
             ('money', 120),
             ('in', 5647),
             ('my', 1786),
             ('purse', 71),
             ('and', 9646),
             ('nothing', 281),
             ('particular', 152),
             ('to', 6497),
             ('interest', 24),
             ('on', 1716),
             ('shore', 26),
             ('i', 7150),
             ('thought', 676),
             ('would', 702),
             ('sail', 104),
             ('about', 1014),
             ('a', 10377),
             ('see', 416),
             ('the', 15540),
             ('watery', 26),
  

In [52]:
vocabulary_size = len(tokenizer.word_counts)

In [53]:
vocabulary_size

2717

In [54]:
# Want this to be a matrix
type(sequences)

list

In [89]:
import numpy as np

In [90]:
sequences = np.array(sequences)

In [91]:
sequences

array([[ 956,   14,  263, ..., 2712,   14,   24],
       [  14,  263,   51, ...,   14,   24,  957],
       [ 263,   51,  261, ...,   24,  957,    5],
       ...,
       [ 952,   12,  166, ...,  262,   53,    2],
       [  12,  166, 2711, ...,   53,    2, 2717],
       [ 166, 2711,    3, ...,    2, 2717,   26]])

In [92]:
from keras.utils import to_categorical

In [93]:
# Grab all columns but the last
X = sequences[:,:-1]
# Grab only the last column
y = sequences[:,-1]

In [94]:
# Note the syntax for factor selection
w = np.array([[1,2,3],[4,5,6]])
display(w)
display(w[:,:-1])
display(w[:,-1])

array([[1, 2, 3],
       [4, 5, 6]])

array([[1, 2],
       [4, 5]])

array([3, 6])

In [95]:
vocabulary_size = len(tokenizer.word_counts)
y = to_categorical(y,num_classes=vocabulary_size+1)

In [96]:
seq_len = X.shape[1]

In [97]:
X.shape

(11312, 25)

In [98]:
# from keras.models import Sequential
from tensorflow.keras.layers import Dense,LSTM,Embedding
from tensorflow.keras.models import Sequential

In [99]:
def create_model(vocabulary_size,seq_len):
    
    model = Sequential()
    # turns positive integers into dense vectors of a fixed size
    model.add(Embedding(input_dim=vocabulary_size, output_dim=seq_len, input_length=seq_len))
    # Common to make this some multiple of your sequence length: seq_len*10 = units = #neurons
    model.add(LSTM(units=seq_len*10, return_sequences=True))
    model.add(LSTM(units=seq_len*10))
    model.add(Dense(units=seq_len*10, activation='relu'))
    
    # output of network - a word
    model.add(Dense(vocabulary_size,activation='softmax'))
    
    model.compile(loss='categorical_crossentropy',optimizer='adam', metrics=['accuracy'])
    
    model.summary()
    
    return model

In [100]:
model = create_model(vocabulary_size+1,seq_len)

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 25, 25)            67950     
_________________________________________________________________
lstm_2 (LSTM)                (None, 25, 250)           276000    
_________________________________________________________________
lstm_3 (LSTM)                (None, 250)               501000    
_________________________________________________________________
dense_6 (Dense)              (None, 250)               62750     
_________________________________________________________________
dense_7 (Dense)              (None, 2718)              682218    
Total params: 1,589,918
Trainable params: 1,589,918
Non-trainable params: 0
_________________________________________________________________


In [101]:
from pickle import dump,load

In [102]:
model.fit(X,y,batch_size=128,epochs=2,verbose=1)

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
Epoch 1/2
11312/11312 [==============================] - 41s 4ms/sample - loss: 6.8054 - acc: 0.0454
Epoch 2/2
11312/11312 [==============================] - 38s 3ms/sample - loss: 6.3756 - acc: 0.0492


In [103]:
model.save('my_mobydick_model.h5')

In [104]:
dump(tokenizer,open('my_simpletokenizer','wb'))

## Generating text based off of a seeded input

In [105]:
# Function to generate new text
def generate_text(model,tokenizer,seq_len,seed_text,num_gen_words):
    """
    Function that takes in some text and returns some predicted words to complete the sentence
    
    model: trained DL model
    tokenizer: association of vocabulary and what ID number goes with what word
    seq_len: length of the sequence of expected texted
    seed_text: input text (preferably the same length as the sequence)
    num_gen_words: number of words to generate
    """
    
    
    from tensorflow.keras.preprocessing.sequence import pad_sequences
    
    output_text = []
    
    input_text = seed_text
    
    for i in range(num_gen_words):
        
        encoded_text = tokenizer.texts_to_sequences([input_text])[0]
        
        pad_encoded = pad_sequences([encoded_text],maxlen=seq_len,truncating='pre')
        
        pred_word_ind = model.predict_classes(pad_encoded,verbose=0)[0]
        
        pred_word = tokenizer.index_word[pred_word_ind]
        
        input_text += ' '+pred_word
        
        output_text.append(pred_word)
    
    return ' '.join(output_text)

In [106]:
text_sequences[0]

['call',
 'me',
 'ishmael',
 'some',
 'years',
 'ago',
 'never',
 'mind',
 'how',
 'long',
 'precisely',
 'having',
 'little',
 'or',
 'no',
 'money',
 'in',
 'my',
 'purse',
 'and',
 'nothing',
 'particular',
 'to',
 'interest',
 'me',
 'on']

In [107]:
import random
random.seed(101)
random_pick = random.randint(0,len(text_sequences))

In [108]:
random_seed_text = text_sequences[random_pick]

In [109]:
random_seed_text

['thought',
 'i',
 'to',
 'myself',
 'the',
 'man',
 "'s",
 'a',
 'human',
 'being',
 'just',
 'as',
 'i',
 'am',
 'he',
 'has',
 'just',
 'as',
 'much',
 'reason',
 'to',
 'fear',
 'me',
 'as',
 'i',
 'have']

In [114]:
seed_text = ' '.join(random_seed_text)

In [115]:
seed_text

"thought i to myself the man 's a human being just as i am he has just as much reason to fear me as i have"

In [123]:
generate_text(model,tokenizer,seq_len,seed_text=seed_text,num_gen_words=25)

"to be seen there was no bad olfactories my own letter was cheerily listening over his hearers who 's more can go have a wearing"

In [120]:
# Lets load in a much more deeply trained model:

In [121]:
from tensorflow.keras.models import load_model

In [122]:
model = load_model('epochBIG.h5')
tokenizer = load(open('epochBIG','rb'))

In [126]:
generate_text(model,tokenizer,seq_len,seed_text=text_sequences[0],num_gen_words=25)

'board existence ha often massa parcel how a thing alone touching broken shy cried sir free on boys my hail here rings a special here'