In [1]:
import numpy as np

In [2]:
from sklearn.datasets import load_iris

In [3]:
iris = load_iris()

In [4]:
type(iris)

sklearn.utils.Bunch

In [5]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [6]:
X = iris.data
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [7]:
y = iris.target
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [8]:
# Want to use one-hot-encoding to use in Keras
# Class_0 --> [1,0,0]
# Class_1 --> [0,1,0]
# Class_2 --> [0,0,1]

In [9]:
from tensorflow.keras.utils import to_categorical

/Users/mbair/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/Users/mbair/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/Users/mbair/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/Users/mbair/opt/anaconda3/lib/python3.7/site-packages/tensorflow/pyth

In [10]:
y = to_categorical(y)
y.shape

(150, 3)

In [11]:
y

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [14]:
# Standardize data

In [15]:
from sklearn.preprocessing import MinMaxScaler

In [16]:
# np.array([5,10,15,20])/20

In [17]:
scaler_obj = MinMaxScaler()

In [18]:
# Only fit to the training features
scaler_obj.fit(X_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [19]:
scaled_X_train = scaler_obj.transform(X_train)
scaled_X_test = scaler_obj.transform(X_test)

In [20]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [21]:
model = Sequential()
# Units: neurons/nodes
# Input_dim: number of features/factors/x-variables to be input
# activation: function for node
model.add(Dense(units=8, input_dim=4, activation='sigmoid'))
model.add(Dense(units=8, input_dim=4, activation='relu'))
model.add(Dense(units=8, input_dim=4, activation='relu'))
model.add(Dense(units=3, activation='softmax'))
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

Instructions for updating:
Colocations handled automatically by placer.


In [22]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 8)                 40        
_________________________________________________________________
dense_1 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_2 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_3 (Dense)              (None, 3)                 27        
Total params: 211
Trainable params: 211
Non-trainable params: 0
_________________________________________________________________


In [23]:
#epochs is the number of times the network "runs" through the entire training dataset
# verbose is the amount of info to output
model.fit(scaled_X_train,y_train,epochs=700,verbose=2)

Instructions for updating:
Use tf.cast instead.
Epoch 1/700
 - 1s - loss: 1.1010 - acc: 0.3500
Epoch 2/700
 - 0s - loss: 1.0969 - acc: 0.3500
Epoch 3/700
 - 0s - loss: 1.0930 - acc: 0.3500
Epoch 4/700
 - 0s - loss: 1.0915 - acc: 0.3500
Epoch 5/700
 - 0s - loss: 1.0892 - acc: 0.3500
Epoch 6/700
 - 0s - loss: 1.0875 - acc: 0.3500
Epoch 7/700
 - 0s - loss: 1.0859 - acc: 0.3500
Epoch 8/700
 - 0s - loss: 1.0843 - acc: 0.3500
Epoch 9/700
 - 0s - loss: 1.0832 - acc: 0.3500
Epoch 10/700
 - 0s - loss: 1.0817 - acc: 0.3500
Epoch 11/700
 - 0s - loss: 1.0793 - acc: 0.3500
Epoch 12/700
 - 0s - loss: 1.0770 - acc: 0.3500
Epoch 13/700
 - 0s - loss: 1.0746 - acc: 0.3500
Epoch 14/700
 - 0s - loss: 1.0728 - acc: 0.3600
Epoch 15/700
 - 0s - loss: 1.0706 - acc: 0.3900
Epoch 16/700
 - 0s - loss: 1.0691 - acc: 0.4200
Epoch 17/700
 - 0s - loss: 1.0668 - acc: 0.4400
Epoch 18/700
 - 0s - loss: 1.0654 - acc: 0.4700
Epoch 19/700
 - 0s - loss: 1.0635 - acc: 0.5100
Epoch 20/700
 - 0s - loss: 1.0618 - acc: 0.5300
E

Epoch 165/700
 - 0s - loss: 0.2846 - acc: 0.9400
Epoch 166/700
 - 0s - loss: 0.2843 - acc: 0.9200
Epoch 167/700
 - 0s - loss: 0.2868 - acc: 0.9300
Epoch 168/700
 - 0s - loss: 0.2846 - acc: 0.9300
Epoch 169/700
 - 0s - loss: 0.2777 - acc: 0.9400
Epoch 170/700
 - 0s - loss: 0.2729 - acc: 0.9300
Epoch 171/700
 - 0s - loss: 0.2695 - acc: 0.9400
Epoch 172/700
 - 0s - loss: 0.2680 - acc: 0.9400
Epoch 173/700
 - 0s - loss: 0.2654 - acc: 0.9400
Epoch 174/700
 - 0s - loss: 0.2625 - acc: 0.9400
Epoch 175/700
 - 0s - loss: 0.2599 - acc: 0.9400
Epoch 176/700
 - 0s - loss: 0.2603 - acc: 0.9300
Epoch 177/700
 - 0s - loss: 0.2595 - acc: 0.9400
Epoch 178/700
 - 0s - loss: 0.2567 - acc: 0.9400
Epoch 179/700
 - 0s - loss: 0.2525 - acc: 0.9300
Epoch 180/700
 - 0s - loss: 0.2496 - acc: 0.9400
Epoch 181/700
 - 0s - loss: 0.2471 - acc: 0.9400
Epoch 182/700
 - 0s - loss: 0.2450 - acc: 0.9400
Epoch 183/700
 - 0s - loss: 0.2431 - acc: 0.9400
Epoch 184/700
 - 0s - loss: 0.2412 - acc: 0.9400
Epoch 185/700
 - 0s 

 - 0s - loss: 0.1178 - acc: 0.9500
Epoch 333/700
 - 0s - loss: 0.1172 - acc: 0.9500
Epoch 334/700
 - 0s - loss: 0.1169 - acc: 0.9500
Epoch 335/700
 - 0s - loss: 0.1237 - acc: 0.9500
Epoch 336/700
 - 0s - loss: 0.1299 - acc: 0.9600
Epoch 337/700
 - 0s - loss: 0.1265 - acc: 0.9600
Epoch 338/700
 - 0s - loss: 0.1219 - acc: 0.9400
Epoch 339/700
 - 0s - loss: 0.1155 - acc: 0.9500
Epoch 340/700
 - 0s - loss: 0.1147 - acc: 0.9500
Epoch 341/700
 - 0s - loss: 0.1144 - acc: 0.9500
Epoch 342/700
 - 0s - loss: 0.1142 - acc: 0.9500
Epoch 343/700
 - 0s - loss: 0.1140 - acc: 0.9500
Epoch 344/700
 - 0s - loss: 0.1147 - acc: 0.9500
Epoch 345/700
 - 0s - loss: 0.1135 - acc: 0.9500
Epoch 346/700
 - 0s - loss: 0.1129 - acc: 0.9500
Epoch 347/700
 - 0s - loss: 0.1129 - acc: 0.9500
Epoch 348/700
 - 0s - loss: 0.1124 - acc: 0.9500
Epoch 349/700
 - 0s - loss: 0.1140 - acc: 0.9500
Epoch 350/700
 - 0s - loss: 0.1124 - acc: 0.9500
Epoch 351/700
 - 0s - loss: 0.1116 - acc: 0.9500
Epoch 352/700
 - 0s - loss: 0.1145

Epoch 500/700
 - 0s - loss: 0.0828 - acc: 0.9600
Epoch 501/700
 - 0s - loss: 0.0834 - acc: 0.9500
Epoch 502/700
 - 0s - loss: 0.0817 - acc: 0.9500
Epoch 503/700
 - 0s - loss: 0.0826 - acc: 0.9500
Epoch 504/700
 - 0s - loss: 0.0857 - acc: 0.9600
Epoch 505/700
 - 0s - loss: 0.0870 - acc: 0.9600
Epoch 506/700
 - 0s - loss: 0.0841 - acc: 0.9600
Epoch 507/700
 - 0s - loss: 0.0842 - acc: 0.9600
Epoch 508/700
 - 0s - loss: 0.0833 - acc: 0.9600
Epoch 509/700
 - 0s - loss: 0.0797 - acc: 0.9500
Epoch 510/700
 - 0s - loss: 0.0805 - acc: 0.9600
Epoch 511/700
 - 0s - loss: 0.0857 - acc: 0.9700
Epoch 512/700
 - 0s - loss: 0.0840 - acc: 0.9700
Epoch 513/700
 - 0s - loss: 0.0834 - acc: 0.9600
Epoch 514/700
 - 0s - loss: 0.0803 - acc: 0.9500
Epoch 515/700
 - 0s - loss: 0.0798 - acc: 0.9500
Epoch 516/700
 - 0s - loss: 0.0799 - acc: 0.9600
Epoch 517/700
 - 0s - loss: 0.0817 - acc: 0.9600
Epoch 518/700
 - 0s - loss: 0.0819 - acc: 0.9600
Epoch 519/700
 - 0s - loss: 0.0826 - acc: 0.9600
Epoch 520/700
 - 0s 

 - 0s - loss: 0.0681 - acc: 0.9700
Epoch 668/700
 - 0s - loss: 0.0658 - acc: 0.9700
Epoch 669/700
 - 0s - loss: 0.0646 - acc: 0.9700
Epoch 670/700
 - 0s - loss: 0.0646 - acc: 0.9700
Epoch 671/700
 - 0s - loss: 0.0648 - acc: 0.9700
Epoch 672/700
 - 0s - loss: 0.0646 - acc: 0.9700
Epoch 673/700
 - 0s - loss: 0.0645 - acc: 0.9600
Epoch 674/700
 - 0s - loss: 0.0657 - acc: 0.9700
Epoch 675/700
 - 0s - loss: 0.0670 - acc: 0.9700
Epoch 676/700
 - 0s - loss: 0.0679 - acc: 0.9700
Epoch 677/700
 - 0s - loss: 0.0693 - acc: 0.9700
Epoch 678/700
 - 0s - loss: 0.0685 - acc: 0.9700
Epoch 679/700
 - 0s - loss: 0.0662 - acc: 0.9700
Epoch 680/700
 - 0s - loss: 0.0647 - acc: 0.9600
Epoch 681/700
 - 0s - loss: 0.0665 - acc: 0.9600
Epoch 682/700
 - 0s - loss: 0.0681 - acc: 0.9700
Epoch 683/700
 - 0s - loss: 0.0680 - acc: 0.9700
Epoch 684/700
 - 0s - loss: 0.0659 - acc: 0.9700
Epoch 685/700
 - 0s - loss: 0.0638 - acc: 0.9700
Epoch 686/700
 - 0s - loss: 0.0624 - acc: 0.9800
Epoch 687/700
 - 0s - loss: 0.0645

In [24]:
model.predict_classes(scaled_X_test)

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 1,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 1, 2, 1, 2])

In [25]:
predictions = model.predict_classes(scaled_X_test)
y_test.argmax(axis=1)

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2])

In [26]:
import pandas as pd
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [27]:
display(pd.DataFrame(confusion_matrix(y_test.argmax(axis=1),predictions), 
                            index=['True0','True1', 'True2'], 
                            columns=['Pred0','Pred1', 'Pred2']))
print(classification_report(y_test.argmax(axis=1),predictions))
print('Accuracy Score:', accuracy_score(y_test.argmax(axis=1),predictions))

Pred0  Pred1  Pred2
True0     19      0      0
True1      0     15      0
True2      0      2     14

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       0.88      1.00      0.94        15
           2       1.00      0.88      0.93        16

    accuracy                           0.96        50
   macro avg       0.96      0.96      0.96        50
weighted avg       0.96      0.96      0.96        50

Accuracy Score: 0.96


In [28]:
# save the results of the model to be re-used
model.save('myfirstmodel.h5')

In [29]:
# load the model
from tensorflow.keras.models import load_model

In [30]:
new_model = load_model('myfirstmodel.h5')

In [31]:
new_model.predict_classes(scaled_X_test)

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 1,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 1, 2, 1, 2])

# Recurrent Neural Networks
> Specifically designed to work with sequence data
* Time series
* Sentences (NLP)
* Audio
* Car Trajectories

<img src='feed_forward_neuron.png'>
<img src='recur_neuron.png'>
<img src='recur_neuron_1.png'>

**Memory Cells:** Nodes that are a function of inputs from previous time steps

<img src='recur_layer.png'>
<img src='recur_layer_1.png'>

# LSTM & GRU
* Long-short term memory
* 

> Help to reduce the "forgetfullness" of RNNs as what was input at $t_{0}$ may lose its influence at $t_{i+j}$

<img src='lstm_cell.png'>

**Input:**
1. $C_{t-1}$: Cell state at $t-1$
2. $h_{t-1}$: outcome of previous cell
3. $x_{t}$: factor of relevance

### First Step: Forget Gate Layer
* We decide what information we are going to "forget", or "throw away", from the cell state
<img src='forget_gate_layer.png'>

### Second Step:
* We decide what to store
<img src='lstm_stage_2.png'>

### Third Step:
* We update the cell state (to send to the next cell state)
<img src='lstm_stage_3.png'>

### Fourth Step:
* We output $h_{t}$
<img src='lstm_stage_4.png'>

**Different kind of LSTMs:**
1. Peephole
2. Gated Recurrent Unit (GRU)

**Peephole**
<img src='lstm_peep.png'>
**GRU**
<img src='lstm_GRU.png'>

# Text Generation with LSTMs with Keras and Python

In [32]:
def read_file(filepath):
    with open(filepath) as f:
        str_text = f.read()
        
        return str_text

In [33]:
# Token and Clean the text

In [34]:
import spacy

In [35]:
# minimize the load by specifiying what to disable
nlp = spacy.load('en_core_web_lg')

In [36]:
nlp.max_length = 1198623

In [37]:
def separate_punc(doc_text):
    import string
    return [token.text.lower() for token in nlp(doc_text) if token.text not in '\n\n \n\n\n!"-#$%&()--.*+,-/:;<=>?@[\\]^_`{|}~\t\n ']
#     return [token.text.lower() for token in nlp(doc_text) if token.text not in [string.punctuation, '\n\n \n\n\n!"']]

In [38]:
d = read_file('moby_dick_four_chapters.txt')

In [39]:
tokens = separate_punc(d)

In [40]:
len(tokens)

11394

In [41]:
# 25 words --> network predict #26

In [42]:
train_len = 25 + 1

text_sequences = []

for i in range(train_len,len(tokens)):
    seq = tokens[i-train_len:i]
    
    text_sequences.append(seq)

In [43]:
type(text_sequences)

list

In [44]:
# Each item in the list is composed of one word to the right of the previous, and less the first
# - shift the text one word right
for i in range(5):
    print(' '.join(text_sequences[i]))
    print()

call me ishmael some years ago never mind how long precisely having little or no money in my purse and nothing particular to interest me on

me ishmael some years ago never mind how long precisely having little or no money in my purse and nothing particular to interest me on shore

ishmael some years ago never mind how long precisely having little or no money in my purse and nothing particular to interest me on shore i

some years ago never mind how long precisely having little or no money in my purse and nothing particular to interest me on shore i thought

years ago never mind how long precisely having little or no money in my purse and nothing particular to interest me on shore i thought i



In [45]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [46]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts(text_sequences)

In [47]:
sequences = tokenizer.texts_to_sequences(text_sequences)

In [48]:
sequences[0]

[964,
 14,
 265,
 51,
 263,
 416,
 87,
 222,
 129,
 111,
 962,
 262,
 50,
 43,
 37,
 321,
 7,
 23,
 555,
 3,
 150,
 261,
 6,
 2704,
 14,
 24]

In [49]:
tokenizer.index_word[956]

'creature'

In [50]:
for i in sequences[0]:
    print(f"{i}: {tokenizer.index_word[i]}")

964: call
14: me
265: ishmael
51: some
263: years
416: ago
87: never
222: mind
129: how
111: long
962: precisely
262: having
50: little
43: or
37: no
321: money
7: in
23: my
555: purse
3: and
150: nothing
261: particular
6: to
2704: interest
14: me
24: on


In [51]:
tokenizer.word_counts

OrderedDict([('call', 27),
             ('me', 2471),
             ('ishmael', 133),
             ('some', 758),
             ('years', 135),
             ('ago', 84),
             ('never', 449),
             ('mind', 164),
             ('how', 321),
             ('long', 374),
             ('precisely', 37),
             ('having', 142),
             ('little', 767),
             ('or', 950),
             ('no', 1029),
             ('money', 120),
             ('in', 5647),
             ('my', 1812),
             ('purse', 71),
             ('and', 9646),
             ('nothing', 281),
             ('particular', 152),
             ('to', 6497),
             ('interest', 24),
             ('on', 1716),
             ('shore', 26),
             ('i', 7176),
             ('thought', 676),
             ('would', 702),
             ('sail', 104),
             ('about', 1014),
             ('a', 10377),
             ('see', 442),
             ('the', 15566),
             ('watery', 26),
  

In [52]:
vocabulary_size = len(tokenizer.word_counts)

In [53]:
vocabulary_size

2709

In [54]:
# Want this to be a matrix
type(sequences)

list

In [55]:
import numpy as np

In [56]:
sequences = np.array(sequences)

In [57]:
sequences

array([[ 964,   14,  265, ..., 2704,   14,   24],
       [  14,  265,   51, ...,   14,   24,  965],
       [ 265,   51,  263, ...,   24,  965,    5],
       ...,
       [ 960,   12,  168, ...,  264,   53,    2],
       [  12,  168, 2703, ...,   53,    2, 2709],
       [ 168, 2703,    3, ...,    2, 2709,   26]])

In [58]:
from keras.utils import to_categorical

Using TensorFlow backend.


In [59]:
# Grab all columns but the last
X = sequences[:,:-1]
# Grab only the last column
y = sequences[:,-1]

In [60]:
# Note the syntax for factor selection
w = np.array([[1,2,3],[4,5,6]])
display(w)
display(w[:,:-1])
display(w[:,-1])

array([[1, 2, 3],
       [4, 5, 6]])

array([[1, 2],
       [4, 5]])

array([3, 6])

In [61]:
vocabulary_size = len(tokenizer.word_counts)
y = to_categorical(y,num_classes=vocabulary_size+1)

In [62]:
seq_len = X.shape[1]

In [63]:
X.shape

(11368, 25)

In [64]:
# from keras.models import Sequential
from tensorflow.keras.layers import Dense,LSTM,Embedding
from tensorflow.keras.models import Sequential

In [65]:
def create_model(vocabulary_size,seq_len):
    
    model = Sequential()
    # turns positive integers into dense vectors of a fixed size
    model.add(Embedding(input_dim=vocabulary_size, output_dim=seq_len, input_length=seq_len))
    # Common to make this some multiple of your sequence length: seq_len*10 = units = #neurons
    model.add(LSTM(units=seq_len*10, return_sequences=True))
    model.add(LSTM(units=seq_len*10))
    model.add(Dense(units=seq_len*10, activation='relu'))
    
    # output of network - a word
    model.add(Dense(vocabulary_size,activation='softmax'))
    
    model.compile(loss='categorical_crossentropy',optimizer='adam', metrics=['accuracy'])
    
    model.summary()
    
    return model

In [66]:
model = create_model(vocabulary_size+1,seq_len)

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 25, 25)            67750     
_________________________________________________________________
lstm (LSTM)                  (None, 25, 250)           276000    
_________________________________________________________________
lstm_1 (LSTM)                (None, 250)               501000    
_________________________________________________________________
dense_4 (Dense)              (None, 250)               62750     
_________________________________________________________________
dense_5 (Dense)              (None, 2710)              680210    
Total params: 1,587,710
Trainable params: 1,587,710
Non-trainable params: 0
_________________________________________________________________


In [67]:
from pickle import dump,load

In [68]:
model.fit(X,y,batch_size=128,epochs=2,verbose=1)

Epoch 1/2
11368/11368 [==============================] - 113s 10ms/sample - loss: 6.8042 - acc: 0.0464
Epoch 2/2
11368/11368 [==============================] - 107s 9ms/sample - loss: 6.3800 - acc: 0.0527


In [69]:
model.save('my_mobydick_model.h5')

In [70]:
dump(tokenizer,open('my_simpletokenizer','wb'))

## Generating text based off of a seeded input

In [71]:
# Function to generate new text
def generate_text(model,tokenizer,seq_len,seed_text,num_gen_words):
    """
    Function that takes in some text and returns some predicted words to complete the sentence
    
    model: trained DL model
    tokenizer: association of vocabulary and what ID number goes with what word
    seq_len: length of the sequence of expected texted
    seed_text: input text (preferably the same length as the sequence)
    num_gen_words: number of words to generate
    """
    
    
    from tensorflow.keras.preprocessing.sequence import pad_sequences
    
    output_text = []
    
    input_text = seed_text
    
    for i in range(num_gen_words):
        
        encoded_text = tokenizer.texts_to_sequences([input_text])[0]
        
        pad_encoded = pad_sequences([encoded_text],maxlen=seq_len,truncating='pre')
        
        pred_word_ind = model.predict_classes(pad_encoded,verbose=0)[0]
        
        pred_word = tokenizer.index_word[pred_word_ind]
        
        input_text += ' '+pred_word
        
        output_text.append(pred_word)
    
    return ' '.join(output_text)

In [72]:
text_sequences[0]

['call',
 'me',
 'ishmael',
 'some',
 'years',
 'ago',
 'never',
 'mind',
 'how',
 'long',
 'precisely',
 'having',
 'little',
 'or',
 'no',
 'money',
 'in',
 'my',
 'purse',
 'and',
 'nothing',
 'particular',
 'to',
 'interest',
 'me',
 'on']

In [73]:
import random
random.seed(101)
random_pick = random.randint(0,len(text_sequences))

In [74]:
random_seed_text = text_sequences[random_pick]

In [75]:
random_seed_text

['and',
 'throwing',
 'the',
 'clothes',
 'to',
 'one',
 'side',
 'he',
 'really',
 'did',
 'this',
 'in',
 'not',
 'only',
 'a',
 'civil',
 'but',
 'a',
 'really',
 'kind',
 'and',
 'charitable',
 'way',
 'i',
 'stood',
 'looking']

In [76]:
seed_text = ' '.join(random_seed_text)

In [77]:
seed_text

'and throwing the clothes to one side he really did this in not only a civil but a really kind and charitable way i stood looking'

In [78]:
generate_text(model,tokenizer,seq_len,seed_text=seed_text,num_gen_words=25)

'the the the the the the the the the the the the the the the the the the the the the the the the the'

In [79]:
# Lets load in a much more deeply trained model:

In [80]:
from tensorflow.keras.models import load_model

In [81]:
model = load_model('epochBIG.h5')
tokenizer = load(open('epochBIG','rb'))

In [82]:
generate_text(model,tokenizer,seq_len,seed_text=text_sequences[0],num_gen_words=25)

'board existence ha often massa parcel how a thing alone touching broken shy cried sir free on boys my hail here rings a special here'