In [1]:
import numpy as np

In [2]:
from sklearn.datasets import load_iris

In [3]:
iris = load_iris()

In [4]:
type(iris)

sklearn.utils.Bunch

In [6]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [7]:
X = iris.data
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [8]:
y = iris.target
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [10]:
# Want to use one-hot-encoding to use in Keras
# Class_0 --> [1,0,0]
# Class_1 --> [0,1,0]
# Class_2 --> [0,0,1]

In [11]:
from keras.utils import to_categorical

In [12]:
y = to_categorical(y)
y.shape

(150, 3)

In [13]:
y

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [16]:
# Standardize data

In [17]:
from sklearn.preprocessing import MinMaxScaler

In [18]:
# np.array([5,10,15,20])/20

array([0.25, 0.5 , 0.75, 1.  ])

In [19]:
scaler_obj = MinMaxScaler()

In [20]:
# Only fit to the training features
scaler_obj.fit(X_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [21]:
scaled_X_train = scaler_obj.transform(X_train)
scaled_X_test = scaler_obj.transform(X_test)

In [22]:
from keras.models import Sequential
from keras.layers import Dense

In [25]:
model = Sequential()
model.add(Dense(units=8, input_dim=4, activation='relu'))
model.add(Dense(units=8, input_dim=4, activation='relu'))
model.add(Dense(units=3, activation='softmax'))
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [26]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_7 (Dense)              (None, 8)                 40        
_________________________________________________________________
dense_8 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_9 (Dense)              (None, 3)                 27        
Total params: 139
Trainable params: 139
Non-trainable params: 0
_________________________________________________________________


In [27]:
#epochs is the number of times the network "runs" through the entire training dataset
# verbose is the amount of info to output
model.fit(scaled_X_train,y_train,epochs=150,verbose=2)

Instructions for updating:
Use tf.cast instead.
Epoch 1/150
 - 2s - loss: 1.2513 - acc: 0.3100
Epoch 2/150
 - 0s - loss: 1.2316 - acc: 0.3100
Epoch 3/150
 - 0s - loss: 1.2108 - acc: 0.3100
Epoch 4/150
 - 0s - loss: 1.1914 - acc: 0.3000
Epoch 5/150
 - 0s - loss: 1.1726 - acc: 0.3000
Epoch 6/150
 - 0s - loss: 1.1540 - acc: 0.3000
Epoch 7/150
 - 0s - loss: 1.1365 - acc: 0.3100
Epoch 8/150
 - 0s - loss: 1.1197 - acc: 0.3100
Epoch 9/150
 - 0s - loss: 1.1027 - acc: 0.5300
Epoch 10/150
 - 0s - loss: 1.0862 - acc: 0.6300
Epoch 11/150
 - 0s - loss: 1.0710 - acc: 0.6400
Epoch 12/150
 - 0s - loss: 1.0558 - acc: 0.6400
Epoch 13/150
 - 0s - loss: 1.0417 - acc: 0.6400
Epoch 14/150
 - 0s - loss: 1.0279 - acc: 0.6400
Epoch 15/150
 - 0s - loss: 1.0147 - acc: 0.6400
Epoch 16/150
 - 0s - loss: 1.0014 - acc: 0.6400
Epoch 17/150
 - 0s - loss: 0.9888 - acc: 0.6400
Epoch 18/150
 - 0s - loss: 0.9763 - acc: 0.6500
Epoch 19/150
 - 0s - loss: 0.9639 - acc: 0.6500
Epoch 20/150
 - 0s - loss: 0.9517 - acc: 0.6500
E

In [29]:
model.predict_classes(scaled_X_test)

array([1, 0, 2, 1, 2, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 1,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2])

In [30]:
predictions = model.predict_classes(scaled_X_test)
y_test.argmax(axis=1)

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2])

In [33]:
import pandas as pd
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [38]:
display(pd.DataFrame(confusion_matrix(y_test.argmax(axis=1),predictions), 
                            index=['True0','True1', 'True2'], 
                            columns=['Pred0','Pred1', 'Pred2']))
print(classification_report(y_test.argmax(axis=1),predictions))
print('Accuracy Score:', accuracy_score(y_test.argmax(axis=1),predictions))

Pred0  Pred1  Pred2
True0     19      0      0
True1      0     13      2
True2      0      1     15

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       0.93      0.87      0.90        15
           2       0.88      0.94      0.91        16

   micro avg       0.94      0.94      0.94        50
   macro avg       0.94      0.93      0.94        50
weighted avg       0.94      0.94      0.94        50

Accuracy Score: 0.94


In [39]:
# save the results of the model to be re-used
model.save('myfirstmodel.h5')

In [40]:
# load the model
from keras.models import load_model

In [42]:
new_model = load_model('myfirstmodel.h5')

# Recurrent Neural Networks
> Specifically designed to work with sequence data
* Time series
* Sentences (NLP)
* Audio
* Car Trajectories

<img src='feed_forward_neuron.png'>
<img src='recur_neuron.png'>
<img src='recur_neuron_1.png'>

**Memory Cells:** Nodes that are a function of inputs from previous time steps

<img src='recur_layer.png'>
<img src='recur_layer_1.png'>

# LSTM & GRU
* Long-short term memory
* 

> Help to reduce the "forgetfullness" of RNNs as what was input at $t_{0}$ may lose its influence at $t_{i+j}$

<img src='lstm_cell.png'>

**Input:**
1. $C_{t-1}$: Cell state at $t-1$
2. $h_{t-1}$: outcome of previous cell
3. $x_{t}$: factor of relevance

### First Step: Forget Gate Layer
* We decide what information we are going to "forget", or "throw away", from the cell state
<img src='forget_gate_layer.png'>

### Second Step:
* We decide what to store
<img src='lstm_stage_2.png'>

### Third Step:
* We update the cell state (to send to the next cell state)
<img src='lstm_stage_3.png'>

### Fourth Step:
* We output $h_{t}$
<img src='lstm_stage_4.png'>

**Different kind of LSTMs:**
1. Peephole
2. Gated Recurrent Unit (GRU)

**Peephole**
<img src='lstm_peep.png'>
**GRU**
<img src='lstm_GRU.png'>